blank_issues_enabled: false
contact_links:
  - name: Security vulnerability
    url: https://github.com/pntech20/resource-safe-execution/security/advisories/new
    about: Report vulnerabilities privately
